### ISSUE TITLE
installer download fails

### ISSUE THREAD

**Issue by StephenRansom** [starlight/lux-desktop#3]
after installing the "lux-install.exe" from the blog, I run it and always receive a download failed message for setup-x86_64.exe. 

I have tried with my firewall turned completely off, but still receive the error.

**Comment by StephenRansom** [comment]
after an hour, the issue resolved itself

**Comment by isaacwhanson** [comment]
The cygwin setup executable is hosted and maintained by cygwin.com.  it was probably down for a bit.  The installer for my project does a simple http download of the setup exe and runs it to install packages.  Firewalls should never need to be disabled.  Thanks for the report.
