### ISSUE TITLE
XFCE intercepts Windows Logo key

### ISSUE THREAD

**Issue by aikeru** [starlight/lux-desktop#4]
Hey, this is a really cool project! It was pretty easy to get up and running and I love where this is headed for those of us stuck on Windows that want more linux flavor.

When I open a terminal from the Xfce dock and then, from within the terminal, press the windows key (ie: to start searching for something), it seems that it's intercepting the key press.

Is there a way around this?

Apologies if this isn't the correct repository for this particular issue.

**Comment by isaacwhanson** [comment]
Ah yes, I see what you mean.  You can still activate the Windows Button using "CTRL + ESC" as a workaround.  This will also work in non-xfce apps.

If you would like the windows button to do something different in XFCE apps, you can map the key in Settings --> Keyboard.

I do not currently have a solution that triggers the Windows Start Menu using the *Windows button* in XFCE, you must use CTRL+ESC for now.  Thanks for the bug report, I will look into this further.

**Comment by isaacwhanson** [comment]
This has been fixed.  Now, there is a default keyboard shortcut config file placed here:

~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml

If the file already exists, it will not be overwritten - and you will not get the win-key support.

This adds a mapping for the win-key to launch a short script, which opens the start-menu.

thanks again for the report.

**Comment by aikeru** [comment]
Thanks for the quick response! I wasn't sure how to update to take advantage of this.
I ran ```spm -u``` but it still seems to behave the same.

After updating I did notice the new XML file and VBScript, but I had to add the key/script entry in Application Shortcuts manually.

Great job on a solution! :)

**Comment by isaacwhanson** [comment]
probably should have mentioned that the default home-directory dotfiles from /etc/skel only get copied when you relaunch a terminal/xfce, and if they don't already exist.  But it is working now, yes?  I just did a fresh install of my system to test the new feature, and it seems ok for me.

**Comment by aikeru** [comment]
Yup! Issue seems to be resolved on my end. Thanks again!

**Comment by isaacwhanson** [comment]
No, thank *you*.  the whole reason I made this public was to get bug reports.  If you see anything else, even trivial stuff, I would appreciate a bug report.  take care.
