### ISSUE TITLE
Latest installer hangs after installation

### ISSUE THREAD

**Issue by SharkWipf** [starlight/lux-desktop#8]
Just tried to install Lux-desktop on another machine, right after a clean Win10 Pro install.  
It seems the installer refuses to go past the final (?) installation step, getting stuck on `/etc/defaults/etc/profile.d/01-mount.sh`.  
The file does get installed successfully and canceling the installer seems to put all files in place, but cygwin terminal doesn't get installed and other post-installation steps don't complete either, leaving you with an incomplete installation.  

The installer (as you know) worked fine before the latest update, I don't see anything that could have broken it in the last commits, I'd guess something changed in the packaging of the installer?  

Version: lux-desktop-201703152255-1  

![image](https://cloud.githubusercontent.com/assets/751205/24055857/03a4cd36-0b42-11e7-8117-0163e96d01d7.png)

**Comment by isaacwhanson** [comment]
@SharkWipf the installer hasn't changed at all - the same executable as before, and I just did a fresh lux install after a clean Win 10 Pro install and it all worked fine yesterday.  I will try this again this afternoon and see if I can reproduce.

**Comment by SharkWipf** [comment]
I think I've just found the issue, minutes after opening it.  
I used the Microsoft reset tool (not the built-in one, the more thorough one you have to download), it is supposed to completely erase everything before reinstalling, but it seems it didn't remove the lux-x86_64 folder.  
As a result, my user, as well as, interestingly, the administrator account, don't have permission to remove it anymore.  
So yeah, this issue is PEBCAK so I'll close it now.
